### ISSUE TITLE
Compile error on Mac

### ISSUE THREAD

**Issue by psaintjust** [deepfryed/beanstalk-client#32]
beanstalk-client/beanstalk.c:267:74: error: use of undeclared identifier 'MSG_NOSIGNAL'
return send(fd, message, size, bs_poll ? MSG_DONTWAIT|MSG_NOSIGNAL : MSG_NOSIGNAL);

MSG_NOSIGNAL is not defined on Mac OSX - introduced by #31

**Comment by lippenyit** [comment]
Put the following line in beanstalk.c after includes:
#define MSG_NOSIGNAL 0x2000 /* don't raise SIGPIPE */
